version: 2

seeds:
  - name: seed_coe__competition_results__fixed_data
    config:
      column_types:
        is_fixed: INTEGER
        OFFSET: INTEGER
        year: INTEGER
        program: STRING
        award_category: STRING
        url: STRING
        coe_competition_result: JSON